import axios from "axios";
import nodemailer from "nodemailer";
import { createClient } from "@/lib/supabase-server";
import { getTopJobs, sendJobEmailReport } from "@/lib/job-worker";


async function getTopVideos(queries: string[], maxResults = 10) {
  const publishedAfter = new Date();
  publishedAfter.setHours(publishedAfter.getHours() - 48);
  const timestamp = publishedAfter.toISOString();

  const apiKey = process.env.YOUTUBE_API_KEY;
  const allResults = await Promise.all(
    queries.map(async (q) => {
      try {
        const res = await axios.get("https://www.googleapis.com/youtube/v3/search", {
          params: {
            key: apiKey,
            q,
            part: "snippet",
            type: "video",
            order: "viewCount",
            maxResults: 15,
            publishedAfter: timestamp,
          },
        });
        return res.data.items || [];
      } catch (e) {
        return [];
      }
    })
  );

  const flat = allResults.flat();
  const seenIds = new Set();
  const uniqueItems = flat.filter((v: any) => {
    if (seenIds.has(v.id.videoId)) return false;
    seenIds.add(v.id.videoId);
    return true;
  });

  const uniqueIds = uniqueItems.map((v: any) => v.id.videoId).slice(0, 50);
  if (uniqueIds.length === 0) return [];

  const statsRes = await axios.get("https://www.googleapis.com/youtube/v3/videos", {
    params: {
      key: apiKey,
      id: uniqueIds.join(","),
      part: "statistics,snippet",
    },
  });

  const enriched = statsRes.data.items.map((item: any) => ({
    videoId: item.id,
    title: item.snippet.title,
    channelName: item.snippet.channelTitle,
    publishedAt: item.snippet.publishedAt,
    thumbnail: item.snippet.thumbnails?.high?.url || item.snippet.thumbnails?.default?.url,
    url: `https://www.youtube.com/watch?v=${item.id}`,
    viewCount: parseInt(item.statistics?.viewCount || "0", 10),
  }));

  return enriched.sort((a: any, b: any) => b.viewCount - a.viewCount).slice(0, maxResults);
}

async function sendEmailReport(videos: any[], recipientEmail: string, title: string) {
  const gmailUser = process.env.GMAIL_USER;
  const gmailPass = process.env.GMAIL_PASS;

  if (!gmailUser || !gmailPass) {
    throw new Error("Gmail credentials missing in .env.local");
  }

  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: { user: gmailUser, pass: gmailPass },
  });

  const videoRows = videos.map((v, i) => `
    <div style="margin-bottom: 20px; border-bottom: 1px solid #eee; padding-bottom: 10px;">
      <h3 style="margin: 0;"><a href="${v.url}">${i + 1}. ${v.title}</a></h3>
      <p style="color: #666; font-size: 14px;">👁️ ${v.viewCount.toLocaleString()} views • 📅 ${new Date(v.publishedAt).toLocaleDateString()}</p>
      <img src="${v.thumbnail}" width="200" style="border-radius: 8px;" />
    </div>
  `).join("");

  await transporter.sendMail({
    from: `"YouTube AI Monitor 🤖" <${gmailUser}>`,
    to: recipientEmail,
    subject: `🔥 ${title} — Latest Top Videos`,
    html: `
      <div style="font-family: sans-serif; max-width: 600px; margin: auto;">
        <h1>${title} - Daily Report</h1>
        ${videoRows}
        <hr/>
        <p style="font-size: 12px; color: #999;">Generated by YouTube AI SaaS Dashboard</p>
      </div>
    `,
  });
}

export async function runAgentImmediately(agentId: string, customSupabase?: any) {
  // Use provided client (e.g. Service Role) OR create the standard server client (Cookies)
  const supabase = customSupabase || await createClient();

  try {
    const { data: agent, error } = await supabase
      .from("monitoring_configs")
      .select("*")
      .eq("id", agentId)
      .single();

    if (error || !agent) {
      console.error("Supabase error fetching agent:", error);
      throw new Error(`Agent not found (ID: ${agentId})`);
    }

    if (agent.agent_type === 'job') {
      const jobs = await getTopJobs(
        agent.queries as string[],
        (agent.location as string) || 'Remote',
        agent.max_videos as number || 10
      );
      if (jobs.length > 0) {
        await sendJobEmailReport(jobs, agent.recipient_email as string, agent.title as string);
      }
    } else {
      const apiKey = process.env.YOUTUBE_API_KEY;
      if (!apiKey) throw new Error("YOUTUBE_API_KEY missing in .env.local");
      const videos = await getTopVideos(agent.queries, agent.max_videos || 10);
      
      if (videos.length > 0) {
        await sendEmailReport(videos, agent.recipient_email, agent.title);
      }
    }

    await supabase
      .from("monitoring_configs")
      .update({ 
        last_run_at: new Date().toISOString(), 
        last_run_status: 'success',
        last_run_error: null
      })
      .eq("id", agentId);

    // Add log entry
    await supabase.from('agent_logs').insert({
      agent_id: agentId,
      status: 'success',
      message: `Manual run successful. Report sent to ${agent.recipient_email}.`
    });

    return { success: true };
  } catch (e: any) {
    console.error("Manual Run Error:", e.message);
    
    // Attempt status update even on failure
    await supabase
      .from("monitoring_configs")
      .update({ 
        last_run_at: new Date().toISOString(), 
        last_run_status: 'error',
        last_run_error: e.message
      })
      .eq("id", agentId);

    // Add error log
    await supabase.from('agent_logs').insert({
      agent_id: agentId,
      status: 'error',
      message: e.message
    });
      
    throw e;
  }
}
