import axios from "axios";
import nodemailer from "nodemailer";
import { createClient } from "@/lib/supabase-server";
import { getTopJobs, sendJobEmailReport } from "@/lib/job-worker";
import { createClient as createSupabaseClient } from "@supabase/supabase-js";


async function getTopVideos(queries: string[], maxResults = 10) {
  const publishedAfter = new Date();
  publishedAfter.setHours(publishedAfter.getHours() - 48);
  const timestamp = publishedAfter.toISOString();

  const apiKey = process.env.YOUTUBE_API_KEY;
  const allResults = await Promise.all(
    queries.map(async (q) => {
      try {
        const res = await axios.get("https://www.googleapis.com/youtube/v3/search", {
          params: {
            key: apiKey,
            q,
            part: "snippet",
            type: "video",
            order: "viewCount",
            maxResults: 15,
            publishedAfter: timestamp,
          },
        });
        return res.data.items || [];
      } catch (e) {
        return [];
      }
    })
  );

  const flat = allResults.flat();
  const seenIds = new Set();
  const uniqueItems = flat.filter((v: any) => {
    if (seenIds.has(v.id.videoId)) return false;
    seenIds.add(v.id.videoId);
    return true;
  });

  const uniqueIds = uniqueItems.map((v: any) => v.id.videoId).slice(0, 50);
  if (uniqueIds.length === 0) return [];

  const statsRes = await axios.get("https://www.googleapis.com/youtube/v3/videos", {
    params: {
      key: apiKey,
      id: uniqueIds.join(","),
      part: "statistics,snippet",
    },
  });

  const enriched = statsRes.data.items.map((item: any) => ({
    videoId: item.id,
    title: item.snippet.title,
    channelName: item.snippet.channelTitle,
    publishedAt: item.snippet.publishedAt,
    thumbnail: item.snippet.thumbnails?.high?.url || item.snippet.thumbnails?.default?.url,
    url: `https://www.youtube.com/watch?v=${item.id}`,
    viewCount: parseInt(item.statistics?.viewCount || "0", 10),
  }));

  return enriched.sort((a: any, b: any) => b.viewCount - a.viewCount).slice(0, maxResults);
}

async function sendEmailReport(videos: any[], recipientEmail: string, title: string) {
  const gmailUser = process.env.GMAIL_USER;
  const gmailPass = process.env.GMAIL_PASS;

  if (!gmailUser || !gmailPass) {
    throw new Error("Gmail credentials missing in .env.local");
  }

  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: { user: gmailUser, pass: gmailPass },
  });

  const videoRows = videos.map((v, i) => `
    <div style="margin-bottom: 20px; border-bottom: 1px solid #eee; padding-bottom: 10px;">
      <h3 style="margin: 0;"><a href="${v.url}">${i + 1}. ${v.title}</a></h3>
      <p style="color: #666; font-size: 14px;">👁️ ${v.viewCount.toLocaleString()} views • 📅 ${new Date(v.publishedAt).toLocaleDateString()}</p>
      <img src="${v.thumbnail}" width="200" style="border-radius: 8px;" />
    </div>
  `).join("");

  await transporter.sendMail({
    from: `"YouTube AI Monitor 🤖" <${gmailUser}>`,
    to: recipientEmail,
    subject: `🔥 ${title} — Latest Top Videos`,
    html: `
      <div style="font-family: sans-serif; max-width: 600px; margin: auto;">
        <h1>${title} - Daily Report</h1>
        ${videoRows}
        <hr/>
        <p style="font-size: 12px; color: #999;">Generated by YouTube AI SaaS Dashboard</p>
      </div>
    `,
  });
}

export async function runAgentImmediately(agentId: string, customSupabase?: any) {
  // Use provided client (e.g. Service Role) OR create the standard server client (Cookies)
  const supabase = customSupabase || await createClient();

  try {
    const { data: agent, error } = await supabase
      .from("monitoring_configs")
      .select("*")
      .eq("id", agentId)
      .single();

    if (error || !agent) {
      console.error("Supabase error fetching agent:", error);
      throw new Error(`Agent not found (ID: ${agentId})`);
    }

    const adminSupabase = createSupabaseClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    );

    // Verify Credits & Instant Run Limits
    const { data: profile } = await adminSupabase
      .from("profiles")
      .select("credits, tier, instant_runs_used")
      .eq("id", agent.user_id)
      .single();

    if (!profile) throw new Error("User profile not found.");

    // 1. Credit Check (Universal)
    if (profile.credits < 10) {
      throw new Error("Insufficient Credits: You need at least 10 credits to run this agent.");
    }

    // 2. Instant Run Check (Free Tier specific)
    if (profile.tier === 'free' && profile.instant_runs_used >= 2) {
      throw new Error("Instant Trigger Limit Reached: Free users are limited to 2 manual runs every 7 days. Upgrade to Pro for unlimited instant triggers!");
    }

      let results: any[] = [];
      let emailSent = false;
      if (agent.agent_type === 'job') {
        results = await getTopJobs(
          agent.queries as string[],
          (agent.location as string) || 'Remote',
          agent.max_videos as number || 10
        );
        if (results.length > 0) {
          await sendJobEmailReport(results, agent.recipient_email as string, agent.title as string);
          emailSent = true;
        }
      } else {
        const apiKey = process.env.YOUTUBE_API_KEY;
        if (!apiKey) throw new Error("YOUTUBE_API_KEY missing in .env.local");
        results = await getTopVideos(agent.queries, agent.max_videos || 10);
        
        if (results.length > 0) {
          await sendEmailReport(results, agent.recipient_email, agent.title);
          emailSent = true;
        }
      }

      // Update agent status
      await adminSupabase
        .from("monitoring_configs")
        .update({ 
          last_run_at: new Date().toISOString(), 
          last_run_status: 'success',
          last_run_error: null
        })
        .eq("id", agentId);

      const logMessage = results.length > 0 
        ? `Run successful. Report sent to ${agent.recipient_email}. Cost: 10 Credits.`
        : `Run successful, but no new results found. Email skipped. Cost: 5 Credits (Search fee).`;

      // Add log entry
      await adminSupabase.from('agent_logs').insert({
        agent_id: agentId,
        status: 'success',
        message: logMessage,
        metadata: { results }
      });

      // Deduct Credits & Increment Instant Run Count if Free
      const creditCost = emailSent ? 10 : 5;
      const profileUpdates: any = { 
        credits: Math.max(0, profile.credits - creditCost),
        updated_at: new Date().toISOString()
      };
      
      if (profile.tier === 'free') {
        profileUpdates.instant_runs_used = (profile.instant_runs_used || 0) + 1;
      }

      await adminSupabase
        .from("profiles")
        .update(profileUpdates)
        .eq("id", agent.user_id);

    return { success: true };
  } catch (e: any) {
    console.error("Manual Run Error:", e.message);
    
    const adminSupabase = createSupabaseClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    );

    // Attempt status update even on failure
    await adminSupabase
      .from("monitoring_configs")
      .update({ 
        last_run_at: new Date().toISOString(), 
        last_run_status: 'error',
        last_run_error: e.message
      })
      .eq("id", agentId);

    // Add error log
    await adminSupabase.from('agent_logs').insert({
      agent_id: agentId,
      status: 'error',
      message: e.message
    });
      
    throw e;
  }
}
